FROM golang:1.16-alpine
RUN apk add build-base

WORKDIR /app

COPY ./migrations ./migrations

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

CMD goose --dir=migrations postgres "postgresql://postgres:postgres@db:5432/spa?sslmode=disable" up