FROM node:16.13.0 as client

WORKDIR /app/client

COPY ./client-posts-app-for-server/package.json /app/client

COPY ./client-posts-app-for-server /app/client

RUN npm install

# RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "dev" ]