FROM golang:1.16-alpine
RUN apk add build-base

WORKDIR /app

COPY ./prod_migration ./prod_migration

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

CMD goose --dir=prod_migration postgres "postgresql://postgres:postgres@db:5432/spa?sslmode=disable" up