version: "3"

services:

  database:
    container_name: db
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./migrations/init:/docker-entrypoint-initdb.d
    networks:
      - default

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - server

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - default

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8081:8081"